name: Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  gate:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Run linter and unit tests in backend
        working-directory: ./backend
        run: |
          uv sync
          uv run ruff check .
          uv run pytest --junitxml=pytest-results.xml

      - uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          check_name: "Backend Unit Tests"
          files: backend/pytest-results.xml

      - name: Run linter and unit tests in frontend
        working-directory: ./frontend
        run: |
          uv sync
          uv run ruff check .
          uv run pytest --junitxml=pytest-results.xml

      - uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          check_name: "Frontend Unit Tests"
          files: frontend/pytest-results.xml

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./backend/Dockerfile
          ignore: DL3018

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./frontend/Dockerfile
          ignore: DL3018

      - name: Start Buddy
        run: |
          ./buddy.sh start

      - name: Run API and E2E Tests
        run: |
          ./buddy.sh test

      - name: Publish Playwright Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          check_name: "Playwright UI Tests"
          files: ./tests/e2e/test-results/results.xml

      - name: Archive Playwright Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report.zip
          path: ./tests/e2e/test-results
          retention-days: 7
